sudo: false
os:
- osx
branches:
  only:
  - master
matrix:
  include:
  - env: BUILD_OPTIONS="--with-cocoa --with-no-frame-refocus --with-imagemagick@6
      --with-multicolor-fonts"
    osx_image: xcode9.2
  - env: BUILD_OPTIONS="--with-cocoa --with-no-frame-refocus --with-imagemagick@6
      --with-multicolor-fonts"
    osx_image: xcode10.1
  - env: BUILD_OPTIONS="--with-cocoa --with-no-frame-refocus --with-imagemagick@6
      --with-multicolor-fonts"
    osx_image: xcode10.2
before_install:
- brew update
- brew tap daviderestivo/emacs-head
script:
- brew install --build-bottle emacs-head $BUILD_OPTIONS
- brew bottle emacs-head
before_deploy:
- export RELEASE_FILES=$(ls *.bottle.tar.gz)
- 'echo ''Deploying files to Bintray: ''$RELEASE_FILES'
deploy:
  provider: bintray
  file: descriptor.json
  user: daviderestivo
  key:
    secure: JNyinkz4kPE/AojtRkJtQSqtbs9KypbB/19sg3Py9r8B7n8GD2U98kgwT/68esZo4J/UL+MT+b992JmRcw3wqQEPvHcg1p2FFi0yMRjcDFqDAyQPWx9ijMzlvQ8YPjYHYSjv+yGU7mgbah1DOurbabQJTh0R85pOU6rYchzkoVisfk0BvOBh87xAwSWjHYyDNBaI1YnqsBAtgP6T0JBBBHT8eH6UrfALAsIeJk6epFLpCS+UnG8qHjfGwwl+dNf+OknsK5n9TO06uZhO6s0LIS+YH6a3Dwn0aSNxb8jA0NbNg4iTPT6Cs2pSVo7Ut7g86qPcz+KErA9imtk6b5rV0zMAEhJFUiGsihrXNk7A7a4j/C3wtqO4OYXsy4vyDAhltXeDUweeF6piri396+SsWNDV3A+RHwKi+Kcp334HNm7GQUwS7mUTLEdZfgzOJA/9GCv5O5jxZyRuJBAbrYWvfL+x3fhVz6SPHmhUbfY5DZnCLCnvyT6vP/v/DM/Q4mxa1g1vp5GBAJSL7DAaZ/6Ybyc3L169nJwqmAn42qddpVeq2vqHvXhzXt+EDk+uhn1Nc/Ywxr7qy363qn9ZX1E0YO2Q+yeiRm2WQKHygojhFdl+6bgox8BrecxP9Ia8gIw9Okx1qCooEVhViO1DE76o7PoogY9BewAU0XgQWngjRMM=
  skip_cleanup: true
